In [11]:
import numpy as np
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print("Original array:\n", arr)

Original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [12]:

print("\nEvery other rows: \n", arr[0:3:2])




Every other rows: 
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]


In [33]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
temp=arr[[0,1,2,3],[3,2,1,0]]
print("\nElement at indices(0,3),(1,2),(2,1),(3,0):\n",temp)


Element at indices(0,3),(1,2),(2,1),(3,0):
 [ 4  7 10 13]


In [29]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("\nOriginal array:",arr)
print("\nReturns every other elements in the array:arr[::2]:",arr[::2])


Original array: [1 2 3 4 5 6 7]

Returns every other elements in the array:arr[::2]: [1 3 5 7]


In [15]:
arr = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2.6, 0, 7, 8], [3, -7, 4, 2.0]])
temp = arr[:2,:3]
print ("\nArray with first 2 rows and 3 columns:\n", temp)


Array with first 2 rows and 3 columns:
 [[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [15]:
import numpy as np
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
cond = arr > 2
temp = arr[cond]
print ("\nElements greater than 2:\n", temp)


Elements greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]


In [17]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))

In [18]:
arr = np.hstack((arr1, arr2))
print("\nHorizondal joining:\n",arr)


Horizondal joining:
 [1 2 3 4 5 6]


In [20]:
arr4=np.vstack((arr1,arr2))
print(arr4)

[[1 2 3]
 [4 5 6]]


In [21]:
arr5=np.dstack((arr1,arr2))
print(arr5)

[[[1 4]
  [2 5]
  [3 6]]]


In [22]:
arr=np.array([1,2,3,4,5,6])
arr6=np.array_split(arr,3)
print(arr)
print(arr6)
print(arr6[0])
print(arr6[1])
print(arr6[2])

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
